# API

## Installation and Usage
npm install
npm run dev
app runs on [3000](http://localhost:3000)

## CRUD: Create Read Update Deleate

## Endpoints Available
- GET `/`
- GET `/fruits`
- GET `/fruits/:name`
- POST `/fruits`
- PATCH `/fruits`
- DELETE `/fruits/:name`


## A middleware logger has been added
:warning: If you forget to add next(), the app will stop running :warning:


## You should be able to define the elements below
- query
- params
- endpoint
- resource